package Class.Project.CarRental.repository;

import Class.Project.CarRental.domain.Car;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class CarDbRepository extends DatabaseRepository<Long, Car> implements CarRepository {

    public CarDbRepository() {
        super("cars");
    }

    @Override
    public Car create(Car car) {
        String sql = "INSERT INTO cars (make, model, rental_price) VALUES (?, ?, ?)";

        // We use RETURN_GENERATED_KEYS to get the ID back from the database
        try (Connection connection = openConnection();
             PreparedStatement statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            statement.setString(1, car.getMake());
            statement.setString(2, car.getModel());
            statement.setDouble(3, car.getRentalPrice());

            statement.executeUpdate();

            // Retrieve the ID generated by the database
            try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    car.setId(generatedKeys.getLong(1));
                }
            }
            return car;
        } catch (SQLException e) {
            throw new RuntimeException("Database error during create car", e);
        }
    }

    @Override
    public Optional<Car> findById(Long id) {
        String sql = "SELECT * FROM cars WHERE id = ?";
        try (Connection connection = openConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setLong(1, id);
            ResultSet resultSet = statement.executeQuery();

            if (resultSet.next()) {
                return Optional.of(extractCar(resultSet));
            }
            return Optional.empty();
        } catch (SQLException e) {
            throw new RuntimeException("Database error during findById", e);
        }
    }

    @Override
    public List<Car> findAll() {
        String sql = "SELECT * FROM cars";
        List<Car> cars = new ArrayList<>();
        try (Connection connection = openConnection();
             PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet resultSet = statement.executeQuery()) {

            while (resultSet.next()) {
                cars.add(extractCar(resultSet));
            }
            return cars;
        } catch (SQLException e) {
            throw new RuntimeException("Database error during findAll cars", e);
        }
    }

    @Override
    public Car update(Car car) throws NotFoundException {
        String sql = "UPDATE cars SET make = ?, model = ?, rental_price = ? WHERE id = ?";
        try (Connection connection = openConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setString(1, car.getMake());
            statement.setString(2, car.getModel());
            statement.setDouble(3, car.getRentalPrice());
            statement.setLong(4, car.getId());

            int rowsUpdated = statement.executeUpdate();
            if (rowsUpdated == 0) {
                throw new NotFoundException("Car with id " + car.getId() + " not found in DB.");
            }
            return car;
        } catch (SQLException e) {
            throw new RuntimeException("Database error during update car", e);
        }
    }

    @Override
    public void deleteById(Long id) throws NotFoundException {
        String sql = "DELETE FROM cars WHERE id = ?";
        try (Connection connection = openConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setLong(1, id);
            int rowsDeleted = statement.executeUpdate();
            if (rowsDeleted == 0) {
                throw new NotFoundException("Car with id " + id + " not found in DB.");
            }
        } catch (SQLException e) {
            throw new RuntimeException("Database error during delete car", e);
        }
    }

    @Override
    public boolean existsById(Long id) {
        String sql = "SELECT 1 FROM cars WHERE id = ?";
        try (Connection connection = openConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setLong(1, id);
            try (ResultSet rs = statement.executeQuery()) {
                return rs.next();
            }
        } catch (SQLException e) {
            throw new RuntimeException("Database error during existsById", e);
        }
    }

    // Helper method to convert SQL row to Java Object
    private Car extractCar(ResultSet rs) throws SQLException {
        long id = rs.getLong("id");
        String make = rs.getString("make");
        String model = rs.getString("model");
        double price = rs.getDouble("rental_price");
        return new Car(id, make, model, price);
    }

    // --- Specific Queries for CarRepository ---

    @Override
    public List<Car> findByManufacturer(String manufacturer) {
        String sql = "SELECT * FROM cars WHERE LOWER(make) = LOWER(?)";
        List<Car> results = new ArrayList<>();
        try (Connection connection = openConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setString(1, manufacturer);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                results.add(extractCar(rs));
            }
            return results;
        } catch (SQLException e) {
            throw new RuntimeException("DB Error", e);
        }
    }

    @Override
    public List<Car> findByModel(String model) {
        String sql = "SELECT * FROM cars WHERE LOWER(model) = LOWER(?)";
        List<Car> results = new ArrayList<>();
        try (Connection connection = openConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setString(1, model);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                results.add(extractCar(rs));
            }
            return results;
        } catch (SQLException e) {
            throw new RuntimeException("DB Error", e);
        }
    }

    @Override
    public List<Car> findByRentalPriceBelow(double maximumPrice) {
        String sql = "SELECT * FROM cars WHERE rental_price <= ?";
        List<Car> results = new ArrayList<>();
        try (Connection connection = openConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setDouble(1, maximumPrice);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                results.add(extractCar(rs));
            }
            return results;
        } catch (SQLException e) {
            throw new RuntimeException("DB Error", e);
        }
    }
}